package com.project.userservice.models;

public enum PermissionName {
    MANAGE_USERS,
    REGISTER_USER,
    VIEW_USER_ACTIVITY,
    CREATE_PROJECT,
    ADMIN_OWN_OPENINGS,
    ADMIN_OTHER_OPENINGS,
    VIEW_PENDING_APPLICATIONS,
    MANAGE_OPENINGS,
    RECRUITER_OWN_OPENINGS,
    RECRUITER_OTHER_OPENINGS,
    CREATE_OPENING,
    VIEW_REPORTS,
    VIEW_ALL_OPENINGS,
    VIEW_APPLIED_OPENINGS
}
